# Install Node.js using packages crafted by NodeSource
---
- name: Check nodejs_version variable
  assert:
    that: nodejs_version is defined
  tags:
    - test

- name: Determine presence of node
  command: which -s node
  ignore_errors: true
  changed_when: false
  register: node_present

- name: Run Nodesource setup script
  when: node_present.rc|int != 0
  script: "{{ ansible_os_family }}/setup_{{ node_major }}.x"
  args:
    creates: /usr/bin/node

- name: Fix yum cache issue
  command: yum clean all
  args:
    warn: false
  changed_when: false
  when: ansible_os_family == 'RedHat'
  tags:
    - skip_ansible_lint

- name: Install Node.js rpm
  when: node_present.rc != '0' and ansible_os_family == 'RedHat'
  yum:
    name: "nodejs"
    update_cache: true
    state: present

- name: Install Node.js package
  when: node_present.rc != '0' and ansible_os_family != 'RedHat'
  package:
    name: "nodejs"
    state: present

- name: Determine version of node
  command: node -v
  changed_when: false
  ignore_errors: true
  register: node_version
  failed_when: node_version.rc|int not in [0,2]

- name: Test version of node
  debug:
    msg: "NodeJS major version mismatch"
  when: not node_version.stdout is search( node_major )
  tags:
    - test

- name: Uninstall Node.js
  when: not node_version.stdout is search( node_major )
  package:
    name: "nodejs"
    state: absent

- name: Uninstall nodesource-release
  when: not node_version.stdout is search( node_major )
  package:
    name: "nodesource-release"
    state: absent

- name: Ensure the system can use the HTTPS transport for APT
  stat:
    path: /usr/lib/apt/methods/https
  register: apt_https_transport
  tags:
    - test

- name: Install HTTPS transport for APT
  apt:
    pkg: apt-transport-https
    state: installed
  when: not apt_https_transport.stat.exists and ansible_os_family == 'Debian'

- name: Run Nodesource setup script
  when: not node_version.stdout is search( node_major )
  script: "{{ ansible_os_family }}/setup_{{ node_major }}.x"

- name: Install Node.js rpm
  when: ansible_os_family == 'RedHat'
  yum:
    name: "nodejs"
    update_cache: true
    state: present

- name: Install Node.js package
  when: ansible_os_family != 'RedHat'
  package:
    name: "nodejs"
    state: present

- name: Install developer tools
  yum:
    name:
      - gcc-c++
      - make
    state: present
  when: ansible_os_family == "RedHat"

- name: Copy goss tests template
  template:
    src: nodejs_goss.yml
    dest: /root/nodejs_goss.yml
    mode: 0640
  tags:
    - test

- name: Install NPM packages
  npm:
    name: "{{ item }}"
    state: present
    global: true
    production: true
  with_items: "{{ base_npm_packages }}"
  changed_when: false  # npm: is not idempotent in ansible <2.4
