---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-nodejs-centos
    image: milcom/centos7-systemd
    privileged: true
  - name: base-nodejs-ubuntu
    image: ubuntu:xenial
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
